version: '2'
services:
    # db: 
    #     image: mysql:5.6
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=root
    #         - MYSQL_USER=sonar
    #         - MYSQL_PASSWORD=sonar
    #         - MYSQL_DATABASE=sonar
    #     volumes:
    #         - /opt/ci-server/mysql:/var/lib/mysql
    #     restart: always

    jenkins:
        image: jenkins:2.0
        volumes:
            # - /opt/ci-server/jenkins:/var/jenkins_home
            - /opt/ci-server/JENKINS_HOME:/var/jenkins_home
        ports:
            - 8080:8080
            - 5001:5000
        user: root
#         links:
#             - db
# #            - artifactory
#             - sonar
        restart: always

    # sonar:
    #     image: sonarqube:5.4
    #     environment:
    #         - SONARQUBE_JDBC_USERNAME=sonar
    #         - SONARQUBE_JDBC_PASSWORD=sonar
    #         - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8
    #     ports:
    #         - 9000:9000
    #         - 9092:9092
    #         - 3306:3306
    #     links:
    #         - db
    #     restart: always

#    artifactory:
#        image: mattgruter/artifactory
#        ports:
#            - 8081:8080
#        volumes:
#            - /opt/ci-server/artifactory/data:/var/opt/jfrog/artifactory/data
#            - /opt/ci-server/artifactory/backup/etc:/var/opt/jfrog/artifactory/etc
#            - /opt/ci-server/artifactory/backup:/var/opt/jfrog/artifactory/backup