FROM jenkins:2.3

USER root
RUN apt-get update \
      && apt-get install -y sudo \
      && rm -rf /var/lib/apt/lists/*
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
 
USER jenkins

COPY plugins.txt .
RUN /usr/local/bin/plugins.sh plugins.txt

EXPOSE 8080 8081 9418
