- name: Copy docker-compose file
  copy: src=docker-compose.yml dest=~/docker-compose.yml
  tags: [copy jenkins-config]
  # become: yes
  # become_user: cicd-user

- name: Provision CI environment with Jenkins and Sonar
  shell: sudo docker-compose up -d chdir=~
  tags: [provision-ci]
  # become: yes
  # become_user: cicd-user