- hosts: cicd
  remote_user: vagrant
  become: yes
  become_method: sudo
  # become_user: cicd-user
  roles:
    - update-apt
    # # - secure-server
    - create-jenkins-home
    - 'marvinpinto.docker'
    - 'franklinkim.docker-compose'
    - provision-ci
    - configure-jenkins