- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  # become_user: cicd-user
  roles:
    # - update-apt
    - 'angstwad.docker_ubuntu'
    - create-jenkins-home
    - provision-ci
    - configure-jenkins